mittagessen/kraken

.travis.yml
README

A very simple setup for testing via Travis. It uses Miniconda to install dependencies and then runs the tests with nose. With ocropy, I originally tried a straight install, but compiling SciPy took so long, it ran out of build time. The conda install is much much quicker, so I just went with that directly here.
You will of course have to enable Travis for your repo before this has a real effect.

Travis CI builds

---

.travis.yml

h5py has a false dependency on it, so it's quicker to install the pre-compiled version from conda than let pip do it. (It's 2 or 3 times longer with cython built-from-source.)
Hopefully, when https://github.com/h5py/h5py/issues/577 is fixed, this install can be dropped.

Temporarily install Cython on Travis.

---

kraken/lib/models.py
requirements.txt

It's only used for `six.PY3` in one place, but you can get that from `future`.

Drop six requirement.

---

kraken/kraken.py

The file is opened in text mode, but writing is attempted with an encoded bytestring. Since these are just lists of numbers, the encoding doesn't really matter, so there's no need to be explicit.

Fix output of segmenter.

---

kraken/repo.py

get/show command  will lead to a requests.get error complaining "get() takes exactly 1 argument (2 given)". You forget to add the 'params' argument,please merge this.

requests needs 'params' argument when passing parameters in url

---

kraken/binarization.py

`escale` is supposed to be a `float`, so it causes a deprecation warning when passed to `np.ones`.
I think this fixes #18, or at least fixes the warnings when running tests.

Use proper integral shape in binarization.

---

.travis.yml
requirements.txt

Protobuf 3 now has a final release, so there's no need to install just the beta. Also, a few packages are now available over conda and can be installed that way now.

Requirement updates

---

kraken/ketos.py

In kraken/binarization.py:nlbin, an exception is thrown which is not handled in ketos.py. Simple try-catch statement added.

Exception handling for binarization in ketos

---

README.rst

Copied over the commands from `kraken.re`'s Quickstart section and changed output file name extensions from `.tif` to `.png`.

Changes related to #88.

---

kraken/binarization.py
kraken/lib/dataset.py
kraken/lib/lineest.py
kraken/lib/util.py
kraken/rpred.py

The type hints for functions that take a PIL Image as input where using the Image submodule and not the Image.Image class.

Fix type hints for PIL.Image.Image.

---

kraken/lib/train.py

collate_sequences from kraken.lib.dataset was not imported, but is needed by train.py (else: NameError)

import missing dependency

---

kraken/lib/dataset.py

This fixes 
* the overriding of the `regions` variable.
* a merged region type not being valid.
* the region type being put in the baselines class mapping.
But it  raises:
```
UserWarning: Using a target size (torch.Size([1, 4, 1200, 876])) that is different to the input size (torch.Size([1, 3, 1200, 876])) is deprecated. Please ensure they have the same size.
return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
```
And ultimately  
```raised unexpected: ValueError('Target and input must have the same number of elements. target nelement (4204800) != input nelement (3153600)')
Traceback (most recent call last):
File "/home/robin/Projects/escriptorium/env/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
R = retval = fun(*args, …
```

Fixes to region training when using BaselineSet.add().

---

kraken/lib/dataset.py
kraken/lib/train.py

Fixes the issue of loading a model, and using its hyper parameters without explicitly setting the count to 0.
It feels a bit weird because restarting a training and training a new model on top of another one goes through the same code/checks?
I changed the hyper_params argument to default to None which allows to only set relevant params in the calling code. So you can just do `hyper_params={'quit': 'early'}` for example instead of loading `kraken.default_specs.SEGMENTATION_HYPER_PARAMS` and overriding what you need. The given params now also supersedes the model's so you can overwrite them.
defaults < model's < user's
I also moved `nn.hyper_params = hyper_params` lower so that it gets applied to just created models as well.
I wanted an early check but if it's correct then I will apply the …

Reset the epoch count when training on top of a model.

---

kraken/contrib/extract_lines.py
kraken/contrib/forced_alignment_overlay.py
kraken/contrib/repolygonize.py
kraken/contrib/segmentation_overlay.py
kraken/ketos.py
kraken/kraken.py

In the help text of some CLI options, some spaces were missing because help messages were split over multiple string segments.
This PR adds the missing spaces.

Fix spacing in help message for CLI options

---

.github/workflows/test.yml
README.rst
kraken/align.py
kraken/contrib/print_word_spreader.py
kraken/ketos.py
kraken/lib/dataset.py
kraken/lib/train.py
tests/test_readingorder.py

These tests try to determine what goes wrong in finding the reading order. This relates to #269, #278 and other issues.
Currently, the `test_is_in_region*` and `test_topsort*` tests pass and only some of the `test_order*` tests pass.
That leads me to believe that something goes wrong in the `reading_order` function, because it doesn't always produce sensible partial reading orders, like `[[0,0],[0,0]]` or `[[1,1],[1,1]]`.
The transformation of (fake) polygonizations of baselines to slices to go into `reading_order` is taken from `polygonal_reading_order`.
After pip-installing `hocr-spec`, `pytest` and `nose`, I can run these tests with `pytest tests/test_readingorder.py`.

Add reading order tests

---

kraken/contrib/segmentation_overlay.py

Fixes parse_palto misspelling in segmentation_overlay.py

---

docs/ketos.rst
kraken/ketos.py

It was already removed for `ketos transcribe` (see issue #180),
but still existed in `ketos train` and `ketos segtrain` where
it is also used for `--partition`.

Drop short option form -p for --pad in all ketos commands

---

kraken/lib/xml.py

In situation where Regions have `:`, this would yield an error, such as the Segmonto syntax:
```xml
<TextRegion id="region_1601885451429_143"  custom="structure {type:NumberingZone:page;}">
```
This fixes this CustomPAGE way to parse the properties.

CustomPageXML parsing: allow ":" in value

---

kraken/serialization.py

The `+ 'Z'` part doesn't look very pretty, but this change provides the UTC timestamp as a string that explicitly shows it's a UTC timestamp. This fixes #327.

Provide timestamp as explicit UTC

---

docs/_static/custom.css
docs/api.rst
docs/api_docs.rst
kraken/kraken.py
kraken/serialization.py
pytest.ini
tests/test_serialization.py

* Adds a function `serialize_segmentation` to save the result of `blla.segment` to e.g. ALTO XML
* Add an example usage of this function in the "API Quickstart", and the reference to the API reference
* Add a test for this new function 
* Make use of it in `kraken segmenter`
```python
with PIL.Image.open('foo.jpg') as im:
res = blla.segment(im, model=model)
size = im.size
with open('foo.xml', 'w') as fp:
fp.write(serialization.serialize_segmentation(res, 'foo.jpg', size, template='alto'))
```

Add utility function serialization.serialize_segmentation

---

kraken/lib/dataset.py
kraken/lib/train.py

Hey @mittagessen,
This is a simple straightforward fix for #340.
Basically, if ArrowIPCDataset aren't build with the same normalization as the one you want to use at training time, this creates unencodable sequences. By rebuilding the alphabet of the dataset, we overcome this issue.
I extracted the transform function to ensure simplification of maintenance of this bit, as it is now applied in two places.

Rebuild Arrow alphabet if the normalization is set.

---

kraken/contrib/repolygonize.py

a small matter, but the function didn’t use its own parameter

use local variable

---

kraken/lib/train.py

If we resize a previous model, load the characters from val and train.
NB: I am not completely sure this is what you meant in #353 but I tried something.

(fix) As for binary automatic split, val chars should be part of the codec in resize/add

---

kraken/lib/train.py

Currently, as a followup to #195, there is a situation where the wrong code is changed to strict False

Move nn.codec to False to prevent wrong codec strict mode change

---

kraken/kraken.py

kraken already shows a good message for the segmentation model,
but the corresponding message for the recognition model just
says 'default':
Loading ANN /home/stweil/src/github/mittagessen/kraken/kraken/blla.mlmodel      ✓
Loading ANN default     ✓
The new code fixes that:
Loading ANN /home/stweil/src/github/mittagessen/kraken/kraken/blla.mlmodel	✓
Loading ANN austriannewspapers.mlmodel	✓
It also fixes the message for the error case (model not found).

Show more informative message for recognition model

---

kraken/contrib/repolygonize.py

In the `kraken/contrib/repolygonize.py` script, if in one of the lines the `Coords` property (the "boundary") is empty then the variable `idx` is not incremented. This creates a misalignment between baselines and boundaries in the following iterations and thus in the exported file.
Getting the line `idx += 1` out of the condition solves the problem.
(Empty boundaries sometimes happen in files exported from eScriptorium.)

Correct alignment bug in repolygonize.py

---

docs/ketos.rst

reStructuredText formats -- as dash, but the documentation for the ketos options should preserve the two single characters, so add an escape character.

Fix formatting of ketos documentation

---

setup.cfg

only a problem since release of numpy 1.24.0 three days ago
("'numpy' has no attribute 'bool'" => apparently it's bool_ now)

make ketos train run again

---

kraken/lib/segmentation.py

This raise seems to have been introduced as you worked on migration ( https://github.com/mittagessen/kraken/commit/90865c2a3266e8da93da5d03bf89e7c8fbce1730 ). This currently breaks segmentation if a single line goes wrong.

Remove former development raise in segmentation

---

kraken/blla.py
kraken/kraken.py
kraken/lib/segmentation.py

Raises error instead of logging them when they are not-blocking, specifically for segmentation avoid stopping completely segmentation for a single wrong line.
Alternative to #442

Propagation of the --raise-on-error for raising non-blocking errors in blla segmentation

---

environment.yml
environment_cuda.yml
kraken/ketos/pretrain.py
kraken/ketos/recognition.py
kraken/ketos/segmentation.py
kraken/lib/train.py

Add a `--precision` option to `ketos train` and `ketos segtrain` to choose the numerical precision to use during training as discussed in #451. It can be set to: '32', 'bf16', '16', '16-mixed', 'bf16-mixed'. The default is `16-mixed`.

add --precision option to ketos train and ketos segtrain

---

kraken/ketos/recognition.py

This PR removes from ketos/recognition a breakpoint statement I wrongfully added with 5459104.

remove breakpoint

---

conda/meta.yaml
environment.yml
environment_cuda.yml
setup.cfg

pin scikit-learn to 1.2.1

---

kraken/lib/arrow_dataset.py

Catch FileNotFoundError for transcription file during binary dataset compilation

---

kraken/metadata.schema.json

`ketos publish` suggests to enter a long description, opens an editor which invites to enter more than a single line, but aborts then because the old pattern only allows a single line.

Allow multi-line description for `ketos publish`

---

conda/meta.yaml
environment.yml
environment_cuda.yml
kraken/lib/train.py
setup.cfg

A new installation of kraken gets torchmetrics 1.1.1 which wants a different import statement for CharErrorRate and WordErrorRate:
```
FutureWarning: Importing `CharErrorRate` from `torchmetrics` was deprecated and will be removed in 2.0. Import `CharErrorRate` from `torchmetrics.text` instead.
FutureWarning: Importing `WordErrorRate` from `torchmetrics` was deprecated and will be removed in 2.0. Import `WordErrorRate` from `torchmetrics.text` instead.
```
Update the import statement and require at least torchmetrics 1.1.0 which introduced the modified import.

Update requirements for torchmetrics and related import statement

---

.github/workflows/test.yml

That test passes and does not need much time, so there is no reason to exclude it from the test.

Enable test_pageseg in GitHub CI test action

---

kraken/contrib/extract_lines.py

Instead of
```
Processing PPN1807526488/1807526488_0011.xml .....................................Processing PPN1807526488/1807526488_0005.xml ....Processing PPN1807526488/1807526488_0004.xml ..Processing PPN1807526488/1807526488_0010.xml .................................................Processing PPN1807526488/1807526488_0006.xml Processing PPN1807526488/1807526488_0012.xml ...................................Processing PPN1807526488/1807526488_0013.xml ........................Processing PPN1807526488/1807526488_0007.xml .....
```
it produces this log output:
```
Processing PPN1807526488/1807526488_0011.xml .....................................
Processing PPN1807526488/1807526488_0005.xml ....
Processing PPN1807526488/1807526488_0004.xml ..
[...]
```

Print separate lines for pages in log output of extract_lines.py

---

kraken/lib/train.py

Hello, I'm new to contributing to open-source projects, but I believe I've identified a minor bug in the logging process.
The bug occurs in the `validation_step` function due to `self.hparams.batch_size`.
Here is my proposed solution: simply change `self.hparams.batch_size` to `self.hparams.hyper_params["batch_size"]`.
I'm not familiar with the entire codebase, but this resolved my issue.

Bug fixed: adjusted the hyperparameters batch_size check for logging to TensorBoard.

---

kraken/templates/alto

This is a fix to the fix :)
The previous fix ends up producing document that you can't import in eScriptorium.

Update alto to not produce Polygon tag on default blocks

---

kraken/lib/arrow_dataset.py
tests/test_arrow_dataset.py

The `_extract_line` and `_extract_path_line` methods currently return a 3-tuple instead of a 2-tuple when there is an error loading the image file. This causes an error when the extract function is called by `map` or `imap_unordered` - it looks like a code error and it took me some digging to determine I was not setting the image path correctly for the `build_binary_dataset` method to be able to load the image files.
I've revised to return two values instead of three and added logging so that it will be easier to diagnose image problems; I wasn't sure if it should be a warning or an error, so kept it as a warning. 
I added a unit test based on the existing tests for the `build_binary_dataset` method.

Adjust return value for image load error in extract line & line path
