kraken/__init__.py, kraken/binarization.py, kraken/html.py, kraken/kraken.py, kraken/lib/__init__.py, kraken/lib/exceptions.py, kraken/lib/lineest.py, kraken/lib/lstm.py, kraken/lib/morph.py, kraken/lib/sl.py, kraken/lib/util.py, kraken/pageseg.py, kraken/rpred.py, setup.py, tests/test_binarization.py, tests/test_html.py, tests/test_pageseg.py, tests/test_rpred.py
Not yet ready to use out of the box, but just a few things that will help writing a single-source package.
=> Python 3 compatibility tweaks

kraken/lib/morph.py
=> Fix minor unit64->uint64 typo.

kraken/kraken.py
I'd prefer things to use the XDG standard. I'm not even sure that POSIX even defines this, so I'm not sure why the option is named that way.
=> Use app dir storage instead of "POSIX".

README.rst
Only the pytorch branch fails, master builds fine.
=> README: show CI status of master in travis badge

kraken/lib/models.py, kraken/lib/train.py
+ Applies segtrain hyper params fix to reco training.
+ Some refacto
+ Adds  `nn.hyper_params = hyper_params` in recognition_train_gen, it wasn't there but maybe it's done somewhere else?
=> Applies segtrain hyper params fix to reco training.

kraken/blla.py
=> fix typo in variable name

docs/vgsl.rst
=> Fix typo (found by codespell)

setup.cfg
=> Allow bug fix releases of Python 3.10

docs/advanced.rst
=> Fix new typos in documentation (found by codespell)

kraken/lib/xml.py
Add import statement for pathlib to fix https://github.com/mittagessen/kraken/issues/426.
=> fix pathlib import in lib/xml.py

kraken/lib/dataset/recognition.py, kraken/lib/dataset/segmentation.py
Disable Opencv multithreading to solve #449
=> disable opencv multithreading

kraken/ketos/recognition.py, kraken/ketos/segmentation.py
Update --warmup option help text as proposed in #452.
=> update --warmup option help text

kraken/ketos/pretrain.py, kraken/ketos/recognition.py, kraken/ketos/segmentation.py
Set default precision to 32-bit to fix issue #456.
=> set default precision to 32-bit

docs/ketos.rst
This PR adds the best practices discussed in #445 and #446 to ketos.rst.
=> add training best practices to ketos.rst

kraken/blla.py, kraken/kraken.py
=> Adding Mixed-Precision prediction for Segmentation

kraken/lib/codec.py
My attempt at solving issue #465
=> Faster decode

docs/ketos.rst, kraken/ketos/recognition.py, kraken/ketos/segmentation.py, kraken/lib/dataset/recognition.py, kraken/lib/dataset/segmentation.py, kraken/lib/train.py, tests/test_merging.py, tests/test_train.py
- refactored augmentation code so that all of it is in one place
- changed parameters of `ElasticTransform` to something more reasonable
- added pixel dropout
- fixed random seed in validation data loader so that augmentation in validation is deterministic
=> A few small changes to augmentation in recognition training

kraken/lib/codec.py
Like #466 but in the other direction ;)
=> Fast encode

kraken/contrib/forced_alignment_overlay.py
Current Force Alignement would break on a different charset, specifically when exporting a non NFKD dataset from eScriptorium and using a model trained on NFKD.
This allows for normalizing the text and avoiding encoding errors.
Fixes #521
=> Include unicode normalization in Forced Alignment

kraken/kraken.py
According to the documentation, models are placed in `$XDG_BASE_DIR` and can be accessed using their name.
While this worked for OCR models, segmentation models were not searched in the kraken config folder. This could be confusing for users.
Now segmentation models can be specified without a path and will be found in the config folder.
Update also the comment for the OCR models.
=> Search segmentation model in XDG_BASE_DIR

kraken/containers.py, kraken/lib/train.py
I had to fix two small bugs in order to train a reading order model. Don't hesitate to close this PL if they've already been fixed.
=> Fix small bugs in the Feature/reading order branch

kraken/ketos/recognition.py
=> Add support fox --fixed-splits on ketos test

README.rst, docs/index.rst
Replace also escriptorium by eScriptorium.
=> Replace broken URL for eScriptorium

kraken/lib/segmentation.py
Speed up legacy polygon extraction using light software optimizations:
- use `np.asarray` instead of `np.array` to convert PIL image to Numpy array
- use `PIL.ImageDraw.Draw` instead of `skimage.draw.polygon` to create the polygon mask
- use a [faster, vectorized version of `skimage.transform.PiecewiseAffineTransform`](https://github.com/scikit-image/scikit-image/issues/6864) instead of vanilla `PiecewiseAffineTransform`
I tested this segmentation on the BiblIA Italian subset (3748 lines). Results:
| Method| Accuracy| Runtime (minutes:seconds)
| ----------- | ----------- | ----------- |
| Current legacy extraction| 97.29% | 56:27 |
| Slightly optimized legacy extraction| 97.33% | 29:26 |
The speedup is more pronounced for straight baselines (closer to 4x). 
The difference in accuracy is …
=> Speed up legacy polygon extraction

kraken/lib/segmentation.py
hello!
the previous mask is creating issues with the polygon. corrected the mask.
=> corrected mask of patch

kraken/contrib/repolygonize.py, kraken/contrib/test_per_file.py
Create a option for scale in the repolygonize function. I have better results with the scale (1000,0) instead the default option (1800,0)
How to use: python kraken/contrib/repolygonize.py -f page --baseline workspace/ocr/*.xml
=> Scale repolygonize

kraken/contrib/test_per_file.py
Function to test each file of a dataset. Shows a summary with CER and WER for each file, allowing to find GT with low efficiency.
*** Only accept page and alto files
Example:
> python venv/kraken/kraken/contrib/test_per_file.py -d cuda:0 --batch-size 12 --workers 10 --threads 10 -u NFD --normalize-whitespace -f page -m workspace/Portuguese.mlmodel workspace/ground_truth/sao_jose_de_piranhas/**/*.xml
>  
> Loading model workspace/Portuguese.mlmodel      ✓
> Evaluating workspace/Portuguese.mlmodel
> Evaluating workspace/ground_truth/sao_jose_de_piranhas/Óbitos_1889-1902/17.xml ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 7/7 0:00:00 0:00:07
>       Char: 3089, CER: 97.8%, WER: 90.4%
> Evaluating workspace/ground_truth/sao_jose_de_piranhas/Óbitos_1889-1902/18.xml …
=> New function for test GT

kraken/kraken.py, kraken/lib/layers.py, kraken/lib/models.py, kraken/lib/train.py, kraken/rpred.py
Adds a softmax temperature option to TorchSeqRecognizer and `kraken ocr` subcommand.
Solves #698.
=> Add temperature option to TorchSeqRecognizer
